Allow bulma-collapsible to work out of the box
lemonsaurus/django-simple-bulma pull request #81
Opened 2021-09-28 09:57 UTC by Ceres445

Added another script which makes the `bulma-collapsible` extension work, you need to use both the script and the extension for it to work. I think it would be easier to just use the extension and make it work, but I'm not sure if that would be possible to implement easily.

2021-09-28 10:13 UTC, lemonsaurus commented
I think it should definitely be doable to marry this script with the bulma-collapsible extension directly. I appreciate the pull request and will probably look at implementing a slightly modified version of this. Is the branch set to be editable by maintainers?

2021-09-28 10:22 UTC, Ceres445 commented
The branch is set to be editable by maintainers

2021-09-28 10:28 UTC, lemonsaurus commented
I can't promise how soon I can look at this, but I will try to make time for it in the near future. Thanks again!

2021-09-28 10:58 UTC, lemonsaurus requested changes
Will rework this a bit to make the script come in automatically when this extension is selected.

2023-08-07 09:16 UTC, lemonsaurus commented
Hi @Ceres445, sorry this has taken forever, I've been a bit gone from the open source scene for an extended period.

I've added a commit now that I think should make the user experience pretty smooth here. Can you test it for me, since I presume you have a project where this is applicable? 

The following statements should be true for this to be working as intended:
- It should automatically add the runner you wrote if the collapsible is added without one.
- If the runner has been added manually to the list of extensions, it should not add a duplicate runner.
- If the collapsible extension is not used, it should not add the runner.
- If "all" is specified in extensions, it should add both collapsible and the runner.

2023-10-01 20:24 UTC, Ceres445 commented
@lemonsaurus I tried to test this on my project, but for some reason my site crashes if i remove `bulma-collapsible-runner` from my config. [Test Project](https://github.com/Ceres445/Team-10-Python-Project)

2025-04-07 10:10 UTC, lemonsaurus commented
This code is now wildly deprecated. I'm gonna turn this into an issue that can be investigated after we've migrated to bulma 1.x

2025-04-07 10:10 UTC, closed without merging